services:
  automatic-test-db:
    image: postgres:latest
    ports:
      - 2345:5432
    environment:
      POSTGRES_USER: blogadmin
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blogdb
      POSTGRES_INITDB_ARGS: '--locale en_US.UTF-8'
    networks:
      - murja_test_network      
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: blogadmin
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blogdb
      POSTGRES_INITDB_ARGS: '--locale en_US.UTF-8'
    networks:
      - murja_test_network

  murja:
    image: ghcr.io/feuery/murja:latest
    ports:
      - 3010:3010
    environment:
      MURJA_DB_HOST: db
      MURJA_E2E: e2e
    networks:
      - murja_test_network
    depends_on:
      - db
      
networks:
  murja_test_network:
